spring:
  application:
    name: simpleapi
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:dcbapp
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  ldap:
    embedded:
      ldif: classpath:localServer.ldif
      base-dn: dc=gaurav,dc=org
      port: 8389